import { expect, test } from "@playwright/test";
test("debug equipment status create as division-scoped user", async ({ page }) => {
  const logs: string[] = [];
  page.on("console", (m) => logs.push(`${m.type()}: ${m.text().slice(0, 300)}`));
  page.on("pageerror", (e) => logs.push(`pageerror: ${e.message.slice(0, 300)}`));
  page.on("response", async (r) => {
    const url = decodeURIComponent(r.url());
    if (url.includes("/equipment/")) logs.push(`resp ${r.status()} ${url.slice(0, 120)} ${r.request().method()}`);
  });
  await page.goto("/");
  await page.getByLabel("用户名").fill("__kne_test");
  await page.getByLabel("密码").fill(process.env.KNE_P ?? "");
  await page.locator('button[type="submit"]').click();
  await expect.poll(() => page.evaluate(() => Boolean(localStorage.getItem("accessToken")))).toBe(true);
  await page.goto("/equipment-status-report");
  await page.waitForTimeout(3000);
  const createButton = page.getByRole("button", { name: /填报设备状态|新增|填\s*报/ }).first();
  console.log("页面按钮:", (await page.locator(".kdos-data-table-toolbar button, .ant-page-header button, button").allInnerTexts()).slice(0, 12).join(" | "));
  await createButton.click();
  await page.waitForTimeout(1200);
  const dialog = page.locator(".ant-modal").last();
  console.log("弹窗标题:", await dialog.locator(".ant-modal-title").innerText().catch(() => "?"));
  const select = dialog.locator(".ant-select").first();
  await select.click();
  await page.waitForTimeout(600);
  const options = page.locator(".ant-select-dropdown:visible .ant-select-item-option");
  const count = await options.count();
  console.log("设备候选数量:", count, "首项:", await options.first().innerText().catch(() => "?"));
  await options.first().click();
  await dialog.getByRole("button", { name: /确\s*定/ }).click();
  await page.waitForTimeout(4000);
  console.log("提交后弹窗仍打开:", await dialog.isVisible().catch(() => false));
  console.log("页面可见错误文本:", (await page.locator(".ant-message, .ant-alert, .ant-form-item-explain").allInnerTexts()).join(" | ").slice(0, 300));
  console.log("LOGS:\n" + logs.slice(-14).join("\n"));
});
