import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Button, Card, Input, InputNumber, Space, Tag, Typography, message } from "antd";
import { api } from "../../api";
import { PageHeader } from "../../shared/legacy-ui";
import { KdosDataTable, kdosDefaultPageSize } from "../../shared/KdosDataTable";

type TablePage = { rows: any[]; total: number; page: number; pageSize: number };
type Scan = { id: string; status: string; stage?: string; rows?: number; counts?: Record<string, number>; groups?: any[]; comparedPairs?: number; skippedBlocks?: number; skippedPairs?: number };
const diff = (left: unknown, right: unknown) => { const a = [...String(left ?? "")], b = [...String(right ?? "")]; let prefix = 0; while (prefix < a.length && prefix < b.length && a[prefix] === b[prefix]) prefix++; return <>{a.map((char, index) => <span key={index} className={index >= prefix ? "rd-diff-char" : undefined}>{char}</span>)}{!a.length && <span className={String(right ?? "") ? "rd-diff-empty" : undefined}>（空）</span>}</>; };

export function RdItemsPage() {
  const [query, setQuery] = useState({ page: 1, pageSize: kdosDefaultPageSize, search: "" });
  const rows = useQuery({ queryKey: ["rd-items", query], queryFn: () => api<TablePage>(`/rd/items?page=${query.page}&pageSize=${query.pageSize}&search=${encodeURIComponent(query.search)}`), placeholderData: (previous) => previous });
  const status = useQuery({ queryKey: ["rd-items-status"], queryFn: () => api<any>("/rd/items/status") });
  const columns = [
    { title: "品号", dataIndex: "itemCode", width: 180, fixed: "left" as const }, { title: "品名", dataIndex: "itemName", width: 180, fixed: "left" as const }, { title: "规格", dataIndex: "specification", width: 240 }, { title: "备注", dataIndex: "remark", width: 220 },
    { title: "归类品", dataIndex: "isGroupItem", width: 90, render: (value: boolean | null) => value == null ? "" : value ? "是" : "否" }, { title: "创建日期", dataIndex: "sourceCreatedAt", width: 170 }, { title: "最后修改日期", dataIndex: "sourceLastModifiedAt", width: 170 }, { title: "修改日期", dataIndex: "sourceModifiedAt", width: 170 }, { title: "创建人", dataIndex: "createdByName", width: 140 }, { title: "最后修改人", dataIndex: "lastModifiedByName", width: 140 }, { title: "修改人", dataIndex: "modifiedByName", width: 140 }, { title: "状态", dataIndex: "status", width: 80 }
  ];
  return <div><PageHeader title="物料数据" actions={<Space><Tag color="blue">当前有效物料 {status.data?.activeItemCount ?? "—"}</Tag><Tag>最近同步 {status.data?.latestSync?.finishedAt ?? status.data?.lastSuccessfulSyncAt ?? "—"}</Tag><Tag color={status.data?.latestSync?.status === "FAILED" ? "error" : "success"}>同步状态 {status.data?.latestSync?.status ?? "—"}</Tag></Space>} /><KdosDataTable resource="rd-items" rowKey="id" loading={rows.isLoading} dataSource={rows.data?.rows} columns={columns} serverData={{ total: rows.data?.total ?? 0, onQueryChange: setQuery }} scroll={{ x: "max-content" }} /></div>;
}

export function RdDuplicatesPage() {
  const client = useQueryClient(); const [itemName, setItemName] = useState(""); const [specification, setSpecification] = useState(""); const [limit, setLimit] = useState(5); const [live, setLive] = useState<any>(); const [scan, setScan] = useState<Scan | null>(null);
  const check = async () => { try { setLive(await api<any>("/rd/material-duplicates/check", { method: "POST", body: JSON.stringify({ itemName, specification, limit }) })); } catch (error) { message.error((error as Error).message); } };
  const start = async () => { try { const result = await api<Scan>("/rd/material-duplicates/scans", { method: "POST" }); setScan(result); client.invalidateQueries({ queryKey: ["rd-scan", result.id] }); } catch (error) { message.error((error as Error).message); } };
  const scanQuery = useQuery({ queryKey: ["rd-scan", scan?.id], enabled: Boolean(scan?.id), queryFn: () => api<Scan>(`/rd/material-duplicates/scans/${scan?.id}?pageSize=50`), refetchInterval: scan?.status === "RUNNING" ? 1200 : false }); const current = scanQuery.data ?? scan;
  return <div><PageHeader title="一物多码检测" /><Alert type="warning" showIcon message="检测结果仅作为辅助判断，不代表系统自动认定为同一物料。" style={{ marginBottom: 12 }} /><Card size="small" title="新物料检测"><Space wrap><Input placeholder="品名" value={itemName} onChange={(event) => setItemName(event.target.value)} style={{ width: 260 }} /><Input placeholder="规格" value={specification} onChange={(event) => setSpecification(event.target.value)} style={{ width: 260 }} /><InputNumber min={1} max={20} value={limit} onChange={(value) => setLimit(value ?? 5)} /><Button type="primary" onClick={() => void check()}>开始检测</Button></Space>{live && <div className="rd-live-results">已检索 {live.rowsScanned} 条，返回 {live.results.length} 条候选{live.results.map((item: any) => <div className="rd-live-item" key={`${item.code}-${item.score}`}><strong>{item.score.toFixed(1)} 分</strong><span>{item.code}</span><span>{item.name}</span><span>{item.spec}</span><small>{item.reason}{item.warnings?.length ? `；${item.warnings.join("；")}` : ""}</small></div>)}</div>}</Card><Card size="small" title="历史检测" style={{ marginTop: 12 }} extra={<Button type="primary" onClick={() => void start()} disabled={current?.status === "RUNNING"}>开始扫描</Button>}>{!current ? <Typography.Text type="secondary">尚未开始扫描</Typography.Text> : <><Typography.Paragraph>状态：{current.status} {current.stage ?? ""}；物料 {current.rows ?? "—"}；比较 {current.comparedPairs ?? "—"} 对；跳过大桶 {current.skippedBlocks ?? "—"} 个 / {current.skippedPairs ?? "—"} 对。</Typography.Paragraph><Space>{Object.entries(current.counts ?? {}).map(([key, value]) => <Tag key={key}>{key}：{value}</Tag>)}</Space>{current.groups?.map((group: any) => <div className="rd-history-group" key={group.id}><div><Tag>{group.kind}</Tag><strong>{group.score ?? "—"} 分</strong> {group.reason}</div>{group.records?.map((record: any, index: number) => { const other = group.records[index ? 0 : 1]; return <div className="rd-ab-row" key={`${record.row}-${index}`}><b>{index ? "B" : "A"}</b><span>{diff(record.code, other?.code)}</span><span>{diff(record.name, other?.name)}</span><span>{diff(record.spec, other?.spec)}</span></div>; })}</div>)}</>}</Card></div>;
}
