import { ConflictException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import type { KdosDatabaseClient } from "@kdos/database";
import type { PoolClient } from "pg";
import { KDOS_DATABASE } from "../planning/drizzle-planning.repository";
import type { PlanningActor } from "../planning/planning.types";
import type { PlanningOperationsRepository } from "./planning-operations.repository";

@Injectable()
export class DrizzlePlanningOperationsRepository implements PlanningOperationsRepository {
  constructor(@Inject(KDOS_DATABASE) private readonly database: KdosDatabaseClient) {}
  async tenantId(code: string) { const result = await this.database.pool.query("SELECT id FROM iam.tenants WHERE code=$1 AND enabled=true", [code]); if (!result.rowCount) throw new NotFoundException("租户不存在或已停用"); return String(result.rows[0].id); }
  private async transaction<T>(tenantId: string, work: (client: PoolClient) => Promise<T>) { const client = await this.database.pool.connect(); try { await client.query("BEGIN"); await client.query("SELECT set_config('app.tenant_id',$1,true)", [tenantId]); const result = await work(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  private async audit(client: PoolClient, tenantId: string, actor: PlanningActor, action: string, resourceType: string, resourceId: string | null, after: unknown) { await client.query(`INSERT INTO audit.audit_logs(tenant_id,user_id,action,resource_type,resource_id,after,source,request_id,trace_id,ip) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`, [tenantId, actor.userId, action, resourceType, resourceId, JSON.stringify(after), actor.source, actor.requestId, actor.traceId ?? null, actor.ip ?? null]); }
  async listWeeklyPeriods(tenantId: string) { return this.transaction(tenantId, async (client) => (await client.query(`SELECT id,sequence,name,start_date AS "startDate",end_date AS "endDate" FROM planning.weekly_plan_periods WHERE tenant_id=$1 ORDER BY sequence`, [tenantId])).rows); }
  async listWeeklyItems(tenantId: string, periodId: string, search = "") { return this.transaction(tenantId, async (client) => (await client.query(`SELECT id,customer_code AS "customerCode",order_number AS "orderNumber",item_number AS "itemNumber",item_name AS "itemName",order_total_quantity AS "orderTotalQuantity",production_unit AS "productionUnit",completion_ratio AS "completionRatio",customer_due_date AS "customerDueDate",review_due_date AS "reviewDueDate",version FROM planning.weekly_plan_items WHERE tenant_id=$1 AND weekly_plan_period_id=$2 AND ($3='' OR concat_ws(' ',customer_code,order_number,item_number,item_name,production_unit) ILIKE '%'||$3||'%') ORDER BY customer_due_date NULLS LAST,order_number,item_number`, [tenantId, periodId, search.trim()])).rows); }
  async syncWeeklyItems(tenantId: string, periodId: string, actor: PlanningActor) { return this.transaction(tenantId, async (client) => {
    const period = await client.query("SELECT id FROM planning.weekly_plan_periods WHERE tenant_id=$1 AND id=$2", [tenantId, periodId]); if (!period.rowCount) throw new NotFoundException("周计划不存在");
    const removedResult = await client.query(`DELETE FROM planning.weekly_plan_items weekly
      WHERE weekly.tenant_id=$1 AND weekly.weekly_plan_period_id=$2 AND
        (weekly.source_order_schedule_id IS NULL OR EXISTS (SELECT 1 FROM marketing.order_schedules schedule
          WHERE schedule.tenant_id=$1 AND schedule.id=weekly.source_order_schedule_id AND schedule.completion_ratio>=100))`, [tenantId, periodId]);
    const result = await client.query(`INSERT INTO planning.weekly_plan_items(tenant_id,weekly_plan_period_id,source_order_schedule_id,customer_code,order_number,item_number,item_name,order_total_quantity,production_unit,completion_ratio,customer_due_date,review_due_date,created_by,updated_by)
      SELECT $1,$2,schedule.id,schedule.customer_code,schedule.order_number,schedule.item_number,schedule.item_name,schedule.order_total_quantity,schedule.production_unit,schedule.completion_ratio,schedule.customer_due_date,item.delivery_date,$3,$3
      FROM marketing.order_schedules schedule LEFT JOIN planning.plan_items item ON item.tenant_id=schedule.tenant_id AND item.id=schedule.source_plan_item_id
      WHERE schedule.tenant_id=$1 AND schedule.completion_ratio<100
      ON CONFLICT(weekly_plan_period_id,order_number,item_number) DO UPDATE SET source_order_schedule_id=EXCLUDED.source_order_schedule_id,customer_code=EXCLUDED.customer_code,item_name=EXCLUDED.item_name,order_total_quantity=EXCLUDED.order_total_quantity,production_unit=EXCLUDED.production_unit,completion_ratio=EXCLUDED.completion_ratio,customer_due_date=EXCLUDED.customer_due_date,review_due_date=COALESCE(EXCLUDED.review_due_date,planning.weekly_plan_items.review_due_date),version=planning.weekly_plan_items.version+1,updated_at=now(),updated_by=$3 RETURNING id`, [tenantId, periodId, actor.userId]);
    const synced = result.rowCount ?? 0; const removed = removedResult.rowCount ?? 0; await this.audit(client, tenantId, actor, "planning.weekly.synced", "WeeklyPlanPeriod", periodId, { synced, removed }); return { synced, removed };
  }); }
  async updateWeeklyDate(tenantId: string, id: string, field: "customer_due_date" | "review_due_date", value: string | null, expectedVersion: number, actor: PlanningActor) { return this.transaction(tenantId, async (client) => { const result = await client.query(`UPDATE planning.weekly_plan_items SET ${field}=$4,version=version+1,updated_at=now(),updated_by=$5 WHERE tenant_id=$1 AND id=$2 AND version=$3 RETURNING *`, [tenantId, id, expectedVersion, value, actor.userId]); if (!result.rowCount) throw new ConflictException("周计划已被其他用户修改，请刷新后重试"); await this.audit(client, tenantId, actor, "planning.weekly.updated", "WeeklyPlanItem", id, { field, value }); return result.rows[0]; }); }
  async listWorkReports(tenantId: string, date: string, search = "") { return this.transaction(tenantId, async (client) => (await client.query(`SELECT id,to_char(work_date,'YYMMDD') AS "displayDate",work_date AS "workDate",customer,order_number AS "orderNumber",item_number AS "itemNumber",item_name AS "itemName",required_quantity AS "requiredQuantity",reported_quantity AS "reportedQuantity",version FROM planning.work_reports WHERE tenant_id=$1 AND work_date=$2 AND ($3='' OR concat_ws(' ',customer,order_number,item_number,item_name) ILIKE '%'||$3||'%') ORDER BY order_number,item_number`, [tenantId, date, search.trim()])).rows); }
  async syncWorkReports(tenantId: string, date: string, actor: PlanningActor) { return this.transaction(tenantId, async (client) => { const result = await client.query(`WITH selected_versions AS (SELECT DISTINCT ON(period_id) id FROM planning.plan_versions WHERE tenant_id=$1 AND status IN ('DRAFT','PUBLISHED','LOCKED') ORDER BY period_id,CASE status WHEN 'DRAFT' THEN 0 WHEN 'PUBLISHED' THEN 1 ELSE 2 END,version_number DESC), source AS (SELECT DISTINCT ON(item.order_number,item.item_number) item.* FROM planning.plan_items item JOIN selected_versions selected ON selected.id=item.plan_version_id WHERE item.tenant_id=$1 ORDER BY item.order_number,item.item_number,item.updated_at DESC)
      INSERT INTO planning.work_reports(tenant_id,work_date,source_plan_item_id,customer,order_number,item_number,item_name,required_quantity,created_by,updated_by)
      SELECT $1,$2,source.id,COALESCE(source.customer_name,source.customer_code),source.order_number,source.item_number,source.item_name,source.order_quantity,$3,$3 FROM source
      ON CONFLICT(tenant_id,work_date,source_plan_item_id) DO UPDATE SET customer=EXCLUDED.customer,order_number=EXCLUDED.order_number,item_number=EXCLUDED.item_number,item_name=EXCLUDED.item_name,required_quantity=EXCLUDED.required_quantity,version=planning.work_reports.version+1,updated_at=now(),updated_by=$3 RETURNING id`, [tenantId, date, actor.userId]); const synced=result.rowCount??0; await this.audit(client,tenantId,actor,"planning.work_report.synced","WorkReport",null,{date,synced}); return { synced }; }); }
  async updateReportedQuantity(tenantId: string, id: string, quantity: string, expectedVersion: number, actor: PlanningActor) { return this.transaction(tenantId, async (client) => { const result=await client.query(`UPDATE planning.work_reports SET reported_quantity=$4,version=version+1,updated_at=now(),updated_by=$5 WHERE tenant_id=$1 AND id=$2 AND version=$3 RETURNING *`,[tenantId,id,expectedVersion,quantity,actor.userId]); if(!result.rowCount) throw new ConflictException("报工记录已被其他用户修改，请刷新后重试"); await this.audit(client,tenantId,actor,"planning.work_report.updated","WorkReport",id,{reportedQuantity:quantity}); return result.rows[0]; }); }
}
