import { Body, Controller, Get, Headers, Ip, Param, Patch, Post, Query, Req, Res, UseGuards } from "@nestjs/common";
import { ApiBearerAuth, ApiTags } from "@nestjs/swagger";
import ExcelJS from "exceljs";
import type { Request, Response } from "express";
import { AuthGuard } from "../../auth";
import type { PlanningActor } from "../planning/planning.types";
import { PlanningOperationsApplicationService } from "./planning-operations.application.service";
type OperationRequest=Request&{user:any;requestId:string};
@ApiTags("主计划运营表") @ApiBearerAuth() @UseGuards(AuthGuard) @Controller("planning-operations")
export class PlanningOperationsController {
  constructor(private readonly application: PlanningOperationsApplicationService) {}
  private actor(req:OperationRequest,tenant:string|undefined,ip:string):PlanningActor{return{tenantCode:tenant||process.env.KDOS_DEFAULT_TENANT_CODE||"KAINAN",userId:req.user?.sub??null,permissions:req.user?.permissions??[],roles:req.user?.roles??[],tableDataScopes:req.user?.tableDataScopes??[],managedOrganizationUnitIds:req.user?.managedOrganizationUnitIds??[],requestId:req.requestId,traceId:String(req.headers["x-trace-id"]??req.requestId),ip,source:req.user?.apiKeyId?"API":"WEB"};}
  @Get("rolling-plan/fields") rollingFields(@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){return this.application.rollingFields(this.actor(req,tenant,ip));}
  @Get("rolling-plan/organization-options") rollingOrganizations(@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){return this.application.rollingOrganizations(this.actor(req,tenant,ip));}
  @Get("rolling-plan/items") rollingItems(@Query() query:Record<string,string|undefined>,@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){let filters={};try{filters=JSON.parse(query.filters??"{}");}catch{filters={};}return this.application.rollingItems({page:Number(query.page),pageSize:Number(query.pageSize),search:query.search,filters,sortField:query.sortField,sortOrder:query.sortOrder==="desc"?"desc":"asc"},this.actor(req,tenant,ip));}
  @Get("weekly-periods") periods(@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){return this.application.weeklyPeriods(this.actor(req,tenant,ip));}
  @Get("weekly-periods/:id/items") items(@Param("id") id:string,@Query() query:Record<string,string|undefined>,@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){let filters={};try{filters=JSON.parse(query.filters??"{}");}catch{filters={};}return this.application.weeklyItems(id,{page:Number(query.page),pageSize:Number(query.pageSize),search:query.search,filters,sortField:query.sortField,sortOrder:query.sortOrder==="desc"?"desc":"asc"},this.actor(req,tenant,ip));}
  @Patch("weekly-items/:id") updateWeekly(@Param("id") id:string,@Body() body:{field:string;value:string|null;expectedVersion:number},@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){return this.application.updateWeekly(id,body,this.actor(req,tenant,ip));}
  @Get("work-reports") reports(@Query() query:Record<string,string|undefined>,@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){let filters={};try{filters=JSON.parse(query.filters??"{}");}catch{filters={};}return this.application.workReports(String(query.date??""),{page:Number(query.page),pageSize:Number(query.pageSize),search:query.search,filters,sortField:query.sortField,sortOrder:query.sortOrder==="desc"?"desc":"asc"},this.actor(req,tenant,ip));}
  @Get("work-reports-export") async exportReports(@Query() query:Record<string,string|undefined>,@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string,@Res() response:Response){let filters={};try{filters=JSON.parse(query.filters??"{}");}catch{filters={};}const rows=await this.application.exportWorkReports(String(query.date??""),{search:query.search,filters,sortField:query.sortField,sortOrder:query.sortOrder==="desc"?"desc":"asc"},this.actor(req,tenant,ip));const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("报工表");const definitions=[["workDate","日期"],["divisionName","事业部"],["customer","客户"],["orderNumber","订单编码"],["itemNumber","品项编码"],["itemName","品名"],["requiredQuantity","需求数量"],["reportedQuantity","报工数量"]] as const;const visible=definitions.filter(([key])=>rows.length===0||rows.some((row)=>Object.prototype.hasOwnProperty.call(row,key)));sheet.columns=visible.map(([key,header])=>({key,header,width:20}));rows.forEach((row)=>sheet.addRow(row));sheet.getRow(1).font={bold:true};response.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");response.setHeader("Content-Disposition",`attachment; filename*=UTF-8''${encodeURIComponent("报工表.xlsx")}`);response.send(Buffer.from(await workbook.xlsx.writeBuffer()));}
  @Post("work-reports/sync") syncReports(@Body() body:{date:string},@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){return this.application.syncWorkReports(body.date,this.actor(req,tenant,ip));}
  @Patch("work-reports/:id") updateReport(@Param("id") id:string,@Body() body:{reportedQuantity:unknown;expectedVersion:number},@Req() req:OperationRequest,@Headers("x-tenant-code") tenant:string|undefined,@Ip() ip:string){return this.application.updateReported(id,body.reportedQuantity,body.expectedVersion,this.actor(req,tenant,ip));}
}
