import { PmcRdProgressQueryService } from './pmc-rd-progress.query.service';
import { PmcRdProgressInternalController } from './pmc-rd-progress.controller';
import { progressScope } from './pmc-rd-progress.scope';
import type { ProgressActor } from './pmc-rd-progress.types';
const actor: ProgressActor={tenantId:'A',userId:'user-1',username:'测试',permissions:['*'],tableDataScopes:[],requestId:'req',source:'web'};
function serviceWith(rows: unknown[][]) { const query=jest.fn().mockImplementation(async()=>rows.shift() ?? []);const dataSource={transaction:jest.fn(async(_isolation:string,work:(m:unknown)=>unknown)=>work({query}))};return {service:new PmcRdProgressQueryService(dataSource as never),query,dataSource}; }
describe('PMC查询权限分页与汇总',()=>{
  it('关闭原始值可筛选且不会成为默认过滤',async()=>{const {service,query}=serviceWith([[],[{total:1}],[{orderCloseRaw:'1'}]]);await service.list({orderClose:'1'},actor);expect(query.mock.calls.at(-1)![0]).toContain('record.order_close_raw');expect(query.mock.calls.at(-1)![1]).toContainEqual(['1']);});
  it('分页、订单号和状态条件在数据库层应用租户与统一筛选',async()=>{const {service,query}=serviceWith([[],[{total:7}],[{id:'1'}]]);const result=await service.list({page:2,pageSize:50,orderNo:'SO-1',rdStatus:'待工艺',onlyIncomplete:'true'},actor);expect(result).toMatchObject({total:7,page:2,pageSize:50});const call=query.mock.calls.at(-1)!;expect(call[0]).toContain('record.tenant_id=$1');expect(call[0]).toContain("NOT IN ('COMPLETE','NOT_APPLICABLE')");expect(call[1]).toContain('A');expect(call[1]).toContainEqual(['WAITING_ROUTING']);expect(call[1].slice(-2)).toEqual([50,50]);});
  it('订单/品号/品名/事业部/三状态多选通过既有IN组成AND，列表与汇总一致',async()=>{
    const filterGroup={logic:'AND',rules:[{field:'orderNo',operator:'in',values:['A','B']},{field:'itemCode',operator:'in',values:['X','Y']},{field:'itemName',operator:'in',values:['同名','名称乙']},{field:'divisionId',operator:'in',values:['0199e000-0000-7000-8000-000000000002','0199e000-0000-7000-8000-000000000003']},{field:'rdStatus',operator:'in',values:['NOT_STARTED','WAITING_ROUTING']},{field:'designBomStatus',operator:'in',values:['NOT_STARTED','COMPLETE']},{field:'routingStatus',operator:'in',values:['NOT_STARTED','COMPLETE']}]};
    const list=serviceWith([[],[{total:2}],[{orderNo:'A',itemCode:'X'},{orderNo:'B',itemCode:'Y'}]]);
    expect((await list.service.list({filterGroup,pageSize:100},actor)).total).toBe(2);
    const count=list.query.mock.calls[1]!;
    for(const rule of filterGroup.rules) expect(count[1]).toContainEqual(rule.values);
    expect(count[0]).toContain('ANY('); expect(count[0]).not.toContain(' OR '); expect(count[0]).toContain('record.tenant_id=$1');
    const summary=serviceWith([[],[{rdStatus:'NOT_STARTED',designBomStatus:'NOT_STARTED',routingStatus:'NOT_STARTED',routingControl:'1',count:2}],[{orderCount:2}]]);
    expect((await summary.service.summary({filterGroup},actor)).itemCount).toBe(2);
    expect(summary.query.mock.calls[1]![1]).toEqual(count[1].slice(0,-2));
    const restricted={...actor,permissions:['pmc-rd-progress:*:read','pmc-rd-progress:orderNo:read'],tableDataScopes:[{resource:'pmc-rd-progress',scope:'ALL'}]};
    await expect(serviceWith([[]]).service.list({filterGroup},restricted)).rejects.toThrow();
  });
  it('最大每页1000且不允许获取全部',async()=>{const {service}=serviceWith([[],[{total:0}],[]]);expect((await service.list({pageSize:0},actor)).pageSize).toBe(100);});
  it('Tenant A查询不绑定Tenant B且设置RLS上下文',async()=>{const {service,query}=serviceWith([[],[{total:0}],[]]);await service.list({},actor);expect(query.mock.calls[0]).toEqual(["SELECT set_config('app.tenant_id',$1,true)",['A']]);expect(query.mock.calls.slice(1).every(call=>call[1][0]==='A')).toBe(true);});
  it('无表读取权限拒绝且不访问数据库',async()=>{const {service,dataSource}=serviceWith([]);await expect(service.list({},{...actor,permissions:[]})).rejects.toThrow('查看权限');expect(dataSource.transaction).not.toHaveBeenCalled();});
  it('隐藏字段不可读取筛选或排序，summary不泄漏隐藏状态',async()=>{const restricted={...actor,permissions:['pmc-rd-progress:*:read','pmc-rd-progress:orderNo:read'],tableDataScopes:[{resource:'pmc-rd-progress',scope:'ALL'}]};const {service,query}=serviceWith([[],[{total:0}],[]]);await service.list({},restricted);expect(query.mock.calls.at(-1)![0]).not.toContain('AS "customerName"');await expect(service.list({customer:'秘密'},restricted)).rejects.toThrow('不能读取或筛选');const second=serviceWith([[],[{rdStatus:'COMPLETE',designBomStatus:'COMPLETE',routingStatus:'COMPLETE',routingControl:'1',count:1}],[{orderCount:1}]]);expect(await second.service.summary({},restricted)).toEqual({orderCount:1,itemCount:1});});
  it('OWN与CUSTOM范围参数化并拒绝NONE和坏规则',()=>{const own={...actor,permissions:['pmc-rd-progress:*:read'],tableDataScopes:[{resource:'pmc-rd-progress',scope:'OWN'}]};const params:unknown[]=[];expect(progressScope(own,params)).toContain('created_by');expect(params).toEqual(['user-1']);expect(progressScope({...own,tableDataScopes:[{resource:'pmc-rd-progress',scope:'NONE'}]},[])).toBe('1=0');expect(progressScope({...own,tableDataScopes:[{resource:'pmc-rd-progress',scope:'CUSTOM',rules:[{fieldKey:'bogus',operator:'EQ',value:'x'}]}]},[])).toBe('1=0');});
  it('summary返回七种状态及适用分母',async()=>{const {service}=serviceWith([[],[{rdStatus:'COMPLETE',designBomStatus:'COMPLETE',routingStatus:'COMPLETE',routingControl:'1',count:2},{rdStatus:'NOT_APPLICABLE',designBomStatus:'NOT_APPLICABLE',routingStatus:'NOT_APPLICABLE',routingControl:'0',count:1},{rdStatus:'ABNORMAL',designBomStatus:'ABNORMAL',routingStatus:'ABNORMAL',routingControl:'0',count:1}],[{orderCount:3}]]);expect(await service.summary({},actor)).toMatchObject({orderCount:3,itemCount:4,applicableItemCount:3,completeItemCount:2,incompleteItemCount:1,overallCompletionRate:'66.67',routingCompletionRate:'100.00',statusCounts:{DESIGN_IN_PROGRESS:0}});});
  it('订单汇总不使用完成阈值',async()=>{const {service}=serviceWith([[],[{total:1}],[{sourceOrderId:'so',orderNo:'SO-1',customerName:'客户',customerCode:'C',items:[...Array.from({length:99},()=>({rdStatus:'COMPLETE'})),{rdStatus:'WAITING_ROUTING'}]}]]);expect((await service.orders({},actor)).rows[0]).toMatchObject({completionRate:'99.00',orderRdStatus:'IN_PROGRESS'});});
  it('伪造详情ID应用数据库范围且返回不存在',async()=>{const {service,query}=serviceWith([[],[]]);await expect(service.detail('11111111-1111-4111-8111-111111111111',actor)).rejects.toThrow('不存在');expect(query.mock.calls[1][0]).toContain('record.tenant_id=$1');});
});
describe('内部同步token和tenant',()=>{
  const application={sync:jest.fn().mockResolvedValue({status:'SUCCESS'})};const controller=new PmcRdProgressInternalController(application as never);let previous:string|undefined;
  beforeAll(()=>{previous=process.env.KDOS_RD_INTERNAL_TOKEN;process.env.KDOS_RD_INTERNAL_TOKEN='test-token';});afterAll(()=>{if(previous===undefined)delete process.env.KDOS_RD_INTERNAL_TOKEN;else process.env.KDOS_RD_INTERNAL_TOKEN=previous;});
  it('拒绝缺失/错误token和跨租户',()=>{expect(()=>controller.sync(undefined,'KAINAN',{mode:'FULL'})).toThrow('凭据');expect(()=>controller.sync('wrong','KAINAN',{mode:'FULL'})).toThrow('凭据');expect(()=>controller.sync('test-token','B',{mode:'FULL'})).toThrow('租户');});
  it('拒绝未知模式并允许合法内部FULL',async()=>{expect(()=>controller.sync('test-token','KAINAN',{mode:'invalid' as never})).toThrow('mode');expect(await controller.sync('test-token','KAINAN',{mode:'FULL'})).toMatchObject({status:'SUCCESS'});expect(application.sync).toHaveBeenCalledWith('FULL',expect.objectContaining({tenantId:'KAINAN'}));});
});
