import { PmcRdProgressApplicationService, contentHash } from './pmc-rd-progress.application.service';
import { PmcRdProgressCalculator } from './pmc-rd-progress.calculator';
import type { ProgressActor, SourceBundle } from './pmc-rd-progress.types';
const actor: ProgressActor={tenantId:'A',userId:'user',username:'同步',permissions:['*'],tableDataScopes:[],requestId:'req',source:'system'};
const bundle: SourceBundle={sourceSnapshotAt:'2026-10-07 12:00:00.000978',consistency:'READ_COMMITTED_CAPTURE',watermark:{snapshotAt:'2026-10-07 12:00:00.000978',sources:{ITEM:{at:'2026-10-07 11:00:00.000978',id:'uuid'}}},candidateLineIds:[],affectedItemIds:[],affectedOrderIds:[],orders:[],plants:[],boms:[],routings:[]};
function harness(facts=bundle) {
  const runner={isTransactionActive:false,connect:jest.fn(),startTransaction:jest.fn(async()=>{runner.isTransactionActive=true;}),commitTransaction:jest.fn(async()=>{runner.isTransactionActive=false;}),rollbackTransaction:jest.fn(async()=>{runner.isTransactionActive=false;}),release:jest.fn(),query:jest.fn(async(sql:string)=>{
    if(sql.includes('pg_try_advisory_lock'))return [{locked:true}];if(sql.includes('SELECT watermark_after'))return [{watermark_after:bundle.watermark}];if(sql.includes('INSERT INTO pmc_rd_progress_sync_runs'))return [{id:'run'}];if(sql.includes('FROM mps_customer_division_mappings')||sql.includes('FROM mps_customer_division_mappings map'))return [];if(sql.includes('SELECT count(*)::int count FROM changed'))return [{count:0}];if(sql.includes('jsonb_to_recordset'))return [{created:1,updated:0}];return [];
  })};
  const reader={read:jest.fn().mockResolvedValue(facts)};
  const service=new PmcRdProgressApplicationService({createQueryRunner:()=>runner} as never,reader as never,new PmcRdProgressCalculator());return {runner,reader,service};
}
describe('PMC整批事务同步',()=>{
  test.each(['FULL','INCREMENTAL'] as const)('%s整批成功才提交高精度水位',async mode=>{const {service,runner,reader}=harness();const result=await service.sync(mode,actor);expect(reader.read).toHaveBeenCalledWith(mode,bundle.watermark,[]);expect(result).toMatchObject({status:'SUCCESS',sourceSnapshotAt:bundle.sourceSnapshotAt,rowsRead:0,watermark:bundle.watermark});expect(runner.commitTransaction).toHaveBeenCalledTimes(2);const update=runner.query.mock.calls.find(call=>call[0].includes("SET status='SUCCESS'"));expect(update).toBeDefined();expect(runner.release).toHaveBeenCalled();});
  it('源读取错误标FAILED且不推进水位',async()=>{const {service,runner,reader}=harness();reader.read.mockRejectedValue(new Error('源库连接失败'));await expect(service.sync('INCREMENTAL',actor)).rejects.toThrow('连接失败');expect(runner.query.mock.calls.some(call=>call[0].includes("SET status='FAILED',completed_at=now(),rows_read"))).toBe(true);expect(runner.query.mock.calls.some(call=>call[0].includes("SET status='SUCCESS'"))).toBe(false);});
  it('写事务失败必须回滚且不推进水位',async()=>{const {service,runner}=harness();const original=runner.query.getMockImplementation()!;runner.query.mockImplementation(async(sql:string)=>{if(sql.includes('SELECT count(*)::int count FROM changed'))throw new Error('写入失败');return original(sql);});await expect(service.sync('FULL',actor)).rejects.toThrow('写入失败');expect(runner.rollbackTransaction).toHaveBeenCalled();expect(runner.query.mock.calls.some(call=>call[0].includes("SET status='SUCCESS'"))).toBe(false);});
  it('并发同步被拒绝且不创建批次',async()=>{const {service,runner}=harness();runner.query.mockResolvedValueOnce([{locked:false}] as never);await expect(service.sync('FULL',actor)).rejects.toThrow('正在运行');expect(runner.query).toHaveBeenCalledTimes(1);expect(runner.release).toHaveBeenCalled();});
  it('普通用户不得触发FULL',async()=>{const {service,runner}=harness();await expect(service.sync('FULL',{...actor,permissions:[]})).rejects.toThrow('只有内部');expect(runner.connect).not.toHaveBeenCalled();});
  it('内容hash稳定且源观察时间不属于内容',()=>{const calc=new PmcRdProgressCalculator();const facts={...bundle,orders:[{order_id:'so',order_line_id:'line',order_no:'SO-1',line_number:1,item_id:'item',item_feature_id:null,item_code:'ITEM',item_name:'物料',item_specification:'',quantity:'1',customer_id:null,customer_code:null,customer_name:null,order_date:null,order_created_at:null,order_last_modified_at:null}],plants:[{item_id:'item',owner_org_id:'plant',item_property:'P',item_routing_control:'0',standard_routing_id:null}]};const row=calc.calculate(facts)[0]!;expect(contentHash(row)).toBe(contentHash(calc.calculate({...facts,sourceSnapshotAt:'2026-10-08 12:00:00.000978'})[0]!));expect(contentHash(row)).not.toBe(contentHash({...row,itemName:'变化'}));});
});
